// app/layout.tsx or app/layout.js

import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// Font setup with `variable` for CSS variable usage
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", // optional but good for performance
});

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
});

// SEO metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${bricolage.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
